# Generated by Django 4.1.4 on 2022-12-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag_scope_scope_unique_tag'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scope',
            name='unique_tag',
        ),
        migrations.AddConstraint(
            model_name='scope',
            constraint=models.UniqueConstraint(fields=('article', 'tag', 'is_main'), name='unique_article_tag'),
        ),
    ]
