# Generated by Django 4.1.4 on 2022-12-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_scope_unique_tag_scope_unique_article_tag'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_tag'),
        ),
    ]
