# Generated by Django 4.1.4 on 2022-12-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_tag_unique_tag'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scope',
            name='unique_article_tag',
        ),
        migrations.AddConstraint(
            model_name='scope',
            constraint=models.UniqueConstraint(fields=('article', 'tag'), name='no_same_tag_twice_for_article'),
        ),
        migrations.AddConstraint(
            model_name='scope',
            constraint=models.UniqueConstraint(fields=('article', 'is_main'), name='only_one_main_tag_for_article'),
        ),
    ]
