# Generated by Django 4.1.4 on 2022-12-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_scope_unique_article_tag_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scope',
            name='only_one_main_tag_for_article',
        ),
        migrations.AddConstraint(
            model_name='scope',
            constraint=models.UniqueConstraint(fields=('article', 'is_main', 'tag'), name='only_one_main_tag_for_article'),
        ),
    ]
