# Generated by Django 4.1.4 on 2022-12-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_scope_only_one_main_tag_for_article_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scope',
            name='only_one_main_tag_for_article',
        ),
        migrations.AddConstraint(
            model_name='scope',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('article', 'is_main'), name='only_one_main_tag_for_article'),
        ),
    ]
