# Generated by Django 4.1.4 on 2022-12-09 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_remove_tag_unique_tag_tag_unique_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='articles.tag', verbose_name='Раздел'),
        ),
    ]
